[WIP] Implement ARP
HeroicKatora/ethox pull request #3
Opened 2019-06-13 12:38 UTC by ackxolotl

2019-06-17 08:38 UTC, HeroicKatora commented
Ah so, `icmp` sollte erst so im Verlauf des Tages sinnvoll verfügbar sein. Ich würd noch nicht darauf rebasen oder mergen weil ich potentiell noch einiges umbauen muss um zero-copy Antworten möglich zu machen (persönliches Muss-Kriterium).

2019-08-01 09:18 UTC, 197g requested changes

2019-08-01 09:18 UTC, 197g commented on src/layer/arp/packet.rs
> +        let capabilities = self.handle.info().capabilities();
Wofür braucht es die hier?

2019-08-01 09:18 UTC, 197g commented on src/layer/arp/tests.rs
> +
Bisschen kurz :smile:

2019-08-01 09:18 UTC, HeroicKatora commented on src/layer/eth/neighbor.rs
> +    fn default() -> Self { Mapping::Address(EthernetAddress::default()) }
Formatting so, und eher `Mapping::LookingFor`.
```
    fn default() -> Self {
        Mapping::LookingFor
    }
```

2019-08-01 09:18 UTC, HeroicKatora commented on src/layer/eth/neighbor.rs
> +        hardware_addr: Mapping,
Ich hätte `fill` ja nicht verändert, sondern eine neue Methode eingeführt um ein `LookingFor` einzutragen. Zumindest nach außen hin das schönere Interface.

2019-08-01 09:18 UTC, HeroicKatora commented on src/layer/eth/neighbor.rs
> +        hardware_addr: Mapping,
Und es spart eine Menge unnötiger Modifikationen in `ip` und `eth`, die sich ja eben nicht mit `arp` befassen wollen.

2019-08-01 09:18 UTC, HeroicKatora commented on src/layer/eth/neighbor.rs
> +    ) -> Option<Mapping> {
`Mapping` ist kein Ergebnis eines lookups. `LookingFor` sollte wie ein noch nicht existenter Eintrag aussehen. Selbiges wie oben mit `fill`, das hier sollte eine zweite Methode sein die von der jetzigen `lookup_pure` benutzt wird.

2019-08-01 09:18 UTC, HeroicKatora commented on src/wire/arp.rs
> +/// A read/write wrapper around an ARP packet buffer.
Erste Verwendung eines Acronyms darf es durchaus erklären. `Address Resolution Protocol (ARP)` hätte es auch getan.

2019-08-01 09:18 UTC, HeroicKatora commented on src/wire/arp.rs
> +}*/
Ganz löschen bitte.

2019-08-01 09:18 UTC, HeroicKatora commented on src/wire/arp.rs
> +    EthernetIpv4Request {
Was hat dir an der vorherigen Repräsentation mit `Operation` nicht gefallen? Sah für mich näher an der Packetdarstellung aus, das Byteformat hängt ja erstmal nur von den Längen der Addressen (also der Kombination `Ethernet+Ipv4`) ab.

2019-08-01 09:18 UTC, HeroicKatora commented on src/wire/arp.rs
> +    EthernetIpv4Request {
Die Änderung hat dafür eine Menge Code weiter unten so gut wie dupliziert.

2019-08-01 09:18 UTC, HeroicKatora commented on src/wire/arp.rs
> +                    " htype={:?} ptype={:?} hlen={:?} plen={:?} op={:?}",
Die (ich nehme an Auto-)Formattierung ist irgendwie komisch. Aber noch in Ordnung.

2019-08-01 09:18 UTC, HeroicKatora commented on src/wire/arp.rs
> +        0x22, 0x23, 0x24, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x41, 0x42, 0x43, 0x44,
Die Autoformattierung hingegen ist sinnlos und macht die Struktur unlesbar.

2019-08-01 12:33 UTC, ackxolotl commented on src/layer/arp/tests.rs
> +
Ja, Testcases kommen noch ^^

2019-08-01 12:38 UTC, ackxolotl commented on src/layer/arp/packet.rs
> +        let capabilities = self.handle.info().capabilities();
Gar nicht, hab ich vergessen zu löschen.

2019-08-01 18:47 UTC, ackxolotl commented on src/wire/arp.rs
> +    EthernetIpv4Request {
Jo, stimmt. Hab ich vorher nicht so bedacht, hab ich rückgängig gemacht.

2019-08-05 10:28 UTC, ackxolotl commented on src/layer/arp/tests.rs
> +
Passt dir der Test so?

2019-08-05 10:53 UTC, HeroicKatora commented on src/layer/arp/tests.rs
> +
Grundsätzlich ja, aber ich würde noch das Resultat parsen und auf Korrektheit checken.

2019-08-05 10:55 UTC, 197g requested changes

2019-08-05 10:55 UTC, HeroicKatora commented on src/layer/eth/endpoint.rs
> +            return self.inner.neighbors.fill(prot_addr, hw_addr, Some(Instant::from_millis(0))).or(Err(Error::Unreachable))
Sieht noch sehr unfertig aus. `Some(Instant::from_millis(0))` is sicher nicht der korrekte Zeitstempel des Requests und wahrscheinlich sofort veraltet.

2019-08-08 16:50 UTC, ackxolotl commented on src/layer/arp/tests.rs
> +
Besser? ;)

2019-08-08 17:05 UTC, HeroicKatora commented on src/layer/arp/tests.rs
> +
Ich weiß zwar nicht genau warum du die Packetbestandteile jeweils mit `as_bytes()` vergleichst, aber grundsätzlich ja. Scheint auch einen Bug gefunden zu haben ;)

2019-08-09 17:05 UTC, 197g approved these changes

2019-08-09 17:28 UTC, ackxolotl commented on src/layer/arp/tests.rs
> +
Ja, stimmt. Und ja, ich kann auch mit den Methoden aus Wire vergleichen wenn dir das lieber is ^^

2019-08-15 14:07 UTC, merged